%YAML:1.0

#===============================================================================
stereo_max_depth: 15.0 # m
stereo_min_depth: 0.5   # m

# Kill off a tracked landmark if it hasn't been observed in this many frames.
# If set to zero, this means that a track dies as soon as it isn't observed in the current frame.
lost_point_lifespan: 0

# Trigger a keyframe if there aren't many landmarks. The StereoFrontend will try to create new
# landmarks for tracking.
trigger_keyframe_min_lmks: 10

# Trigger a keyframe at least every k frames.
# NOTE(milo): More frequent keyframe triggering results in a much better pose estimate.
trigger_keyframe_k: 5

FeatureDetector:
  max_features_per_frame: 100
  subpixel_corners: 0 # bool
  min_distance_btw_tracked_and_detected_features: 5
  gftt_quality_level: 0.03
  gftt_block_size: 5
  gftt_use_harris_corner_detector: 0 # bool
  gftt_k: 0.04

FeatureTracker:
  klt_maxiters: 10
  klt_epsilon: 0.001
  klt_winsize: 21
  klt_max_level: 3

StereoMatcher:
  templ_cols: 31
  templ_rows: 11
  max_disp: 128
  max_matching_cost: 0.15
  bidirectional: 0 # bool
  subpixel_refinement: 0 # bool
