%YAML:1.0

#===============================================================================
max_size_raw_stereo_queue: 100
max_size_smoother_vo_queue: 100
max_size_smoother_imu_queue: 1000
max_size_filter_vo_queue: 100
max_size_filter_imu_queue: 1000

reliable_vision_min_lmks: 12
max_sec_btw_keyframes: 5.0

extra_smoothing_iters: 2
smoother_wait_vision_available: 5.0
smoother_wait_vision_unavailable: 0.1

#===============================================================================
GtsamInferenceParams:
  pose_prior_noise_model: [0.1, 0.1, 0.1, 0.3, 0.3, 0.3]        # rad, rad, rad, m, m, m
  frontend_vo_noise_model: [0.01, 0.01, 0.01, 0.05, 0.05, 0.05] # rad, rad, rad, m, m, m
  lmk_mono_reproj_err_sigma: 2.0    # px in u and v
  lmk_stereo_reproj_err_sigma: 2.0  # px in u and v
  velocity_sigma: 0.1 # m/s

#===============================================================================
StereoFrontend:
  FeatureDetector:
    max_features_per_frame: 200
    subpixel_corners: false
    min_distance_btw_tracked_and_detected_features: 20
    gftt_quality_level: 0.01
    gftt_block_size: 5
    gftt_use_harris_corner_detector: false
    gftt_k: 0.04

  FeatureTracker:
    klt_maxiers: 30
    klt_epsilon: 0.001
    klt_winsize: 21
    klt_max_level: 4

  StereoMatcher:
    templ_cols: 31
    templ_rows: 11
    max_disp: 128
    max_matching_cost: 0.15
    bidirectional: false
    subpixel_refinement: false

#===============================================================================
ImuManager:
  allowed_misalignment_sec: 0.05
  max_queue_size: 1000

  # Sensor noise model parameters.
  accel_noise_sigma:    0.0003924
  gyro_noise_sigma:     0.000205689024915
  accel_bias_rw_sigma:  0.004905
  gyro_bias_rw_sigma:   0.000001454441043

  # Noise model for the zero-prior on IMU bias.
  bias_prior_noise_model_sigma: 0.01

  # Noise model for the IMU bias between factors.
  bias_drift_noise_model_sigma: 0.001

  # Direction of the gravity vector in the world frame.
  # NOTE(milo): Right now, we use a RDF frame for the IMU, so gravity is +y.
  n_gravity: [0, 9.81, 0] # m/s^2
