%YAML:1.0

# Acceleration of gravity in the world frame.
# For example, in a RDF world, n_gravity = [0, 9.81, 0].
# NOTE: This is also used to determine the DEPTH axis (same as gravity).
n_gravity: [0, 9.81, 0]

# https://github.com/kskin/data
stereo_forward:
  camera_left:
    frame_id: camera_left
    body_T_cam:
      cols: 4
      rows: 4
      data: [1.0, 0.0, 0.0, 0.0,
             0.0, 1.0, 0.0, 0.0,
             0.0, 0.0, 1.0, 0.0,
             0.0, 0.0, 0.0, 1.0]

    # Camera specific definitions.
    image_height: 515
    image_width: 645
    camera_model: pinhole
    intrinsics: [952.58, 952.58, 257.0, 322.0] # fx, fy, cx, cy
    distortion_model: radial-tangential
    distortion_coefficients: [0, 0, 0, 0] # Zero means already undistorted.

  camera_right:
    frame_id: camera_right
    body_T_cam:
      cols: 4
      rows: 4
      data: [1.0, 0.0, 0.0, 0.1939,
             0.0, 1.0, 0.0, 0.0,
             0.0, 0.0, 1.0, 0.0,
             0.0, 0.0, 0.0, 1.0]


    # Camera specific definitions.
    image_height: 515
    image_width: 645
    camera_model: pinhole
    intrinsics: [952.58, 952.58, 257.0, 322.0] # fx, fy, cx, cy
    distortion_model: radial-tangential
    distortion_coefficients: [0, 0, 0, 0] # Zero means already undistorted.
